---
abstract: 'A Perl module for clustering data that resides on a low-dimensional manifold in a high-dimensional measurement space'
author:
  - 'Avinash Kak (kak@purdue.edu)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-LinearManifoldDataClusterer
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 2.84
  Graphics::GnuplotIF: 1.6
  List::Util: 1.39
  Math::GSL::Matrix: 0
  Math::Random: 0.71
  POSIX: 1.32
version: 1.0
